import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Box, Container, Heading } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <Container maxW="2xl" centerContent>
      <Head>
        <title>GitHub Commit Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Heading>GitHub Commit Stats</Heading>
      </Box>
    </Container>
  );
};

export default Home;
