import type { NextPage } from "next";
import Head from "next/head";
import { Box, Button, Container, Heading, HStack } from "@chakra-ui/react";
import { useSession, signIn, signOut } from "next-auth/react";
import Link from "next/link";

const Home: NextPage = () => {
  const { data: session, status } = useSession({ required: true });
  const loading = status === "loading";
  const isLoggedIn = status === "authenticated";

  return (
    <Container maxW="2xl" centerContent>
      <Head>
        <title>GitHub Commit Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Heading>GitHub Commit Stats</Heading>
        {loading ? <p>Loading...</p> : null}
        {isLoggedIn ? (
          <>
            <Heading size="md">Logged in.</Heading>
            <HStack>
              <Link href="/dashboard" passHref>
                <Button variant="solid">Dashboard</Button>
              </Link>

              <Button onClick={() => signOut()} variant="outline">
                Sign Out
              </Button>
            </HStack>
          </>
        ) : (
          <Button onClick={() => signIn()}>Sign In</Button>
        )}
      </Box>
    </Container>
  );
};

export default Home;
